/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <stdio.h>
/* Header for class com_scu_dynamicjni_HelloJNI */

#ifndef _Included_com_scu_dynamicjni_HelloJNI
#define _Included_com_scu_dynamicjni_HelloJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_scu_dynamicjni_HelloJNI
 * Method:    printHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_scu_dynamicjni_HelloJNI_printHello
  (JNIEnv *, jclass);

/*
 * Class:     com_scu_dynamicjni_HelloJNI
 * Method:    printString
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_scu_dynamicjni_HelloJNI_printString
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
